version: "3.5"
services:
  web-fe:

    build: .
    env_file:
      - .env
    restart: always
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      - counter-net
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      counter-net:

networks:
  counter-net:



